@extends('docs.layout')

@section('docs-content')
<h1>Two-Factor Authentication (2FA)</h1>

<p class="lead">
    Two-factor authentication adds an extra layer of security to your account by requiring a code from your phone in addition to your password.
</p>

<h2>What is 2FA?</h2>

<p>
    Two-factor authentication (2FA) uses a time-based one-time password (TOTP) generated by an authenticator app on your smartphone. Even if someone obtains your password, they cannot access your account without also having your phone.
</p>

<h2>Grace Period</h2>

<p>
    New users have a <strong>14-day grace period</strong> to set up 2FA. During this time:
</p>

<ul>
    <li>You can log in without 2FA</li>
    <li>A yellow banner will remind you to set up 2FA</li>
    <li>The banner shows how many days remain</li>
</ul>

<p>
    After the grace period expires, you <strong>must</strong> complete 2FA setup to continue using Hay ACS.
</p>

<div class="bg-yellow-50 dark:bg-yellow-900/30 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4 my-4">
    <div class="flex">
        <svg class="w-5 h-5 text-yellow-600 dark:text-yellow-400 mr-3 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path>
        </svg>
        <p class="text-yellow-800 dark:text-yellow-200 text-sm">
            <strong>Recommendation:</strong> Set up 2FA immediately after your first login. Don't wait until the grace period expires.
        </p>
    </div>
</div>

<h2>Supported Authenticator Apps</h2>

<p>You can use any TOTP-compatible authenticator app:</p>

<div class="not-prose grid grid-cols-1 md:grid-cols-2 gap-4 my-6">
    <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
        <h4 class="font-semibold text-gray-900 dark:text-white">Google Authenticator</h4>
        <p class="text-sm text-gray-600 dark:text-gray-400 mt-1">Available for iOS and Android. Free.</p>
    </div>
    <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
        <h4 class="font-semibold text-gray-900 dark:text-white">Microsoft Authenticator</h4>
        <p class="text-sm text-gray-600 dark:text-gray-400 mt-1">Available for iOS and Android. Free.</p>
    </div>
    <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
        <h4 class="font-semibold text-gray-900 dark:text-white">Authy</h4>
        <p class="text-sm text-gray-600 dark:text-gray-400 mt-1">Available for iOS, Android, and desktop. Free.</p>
    </div>
    <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
        <h4 class="font-semibold text-gray-900 dark:text-white">1Password</h4>
        <p class="text-sm text-gray-600 dark:text-gray-400 mt-1">Built-in TOTP support. Paid service.</p>
    </div>
</div>

<h2>Setting Up 2FA</h2>

<h3>Step 1: Access 2FA Setup</h3>

<p>
    After logging in, click on the yellow 2FA setup banner, or navigate to the 2FA setup page from your profile menu.
</p>

<h3>Step 2: Open Your Authenticator App</h3>

<p>
    Open your authenticator app on your phone and look for an option to add a new account. This is usually a "+" button or "Add Account" option.
</p>

<h3>Step 3: Scan the QR Code</h3>

<p>
    Use your authenticator app to scan the QR code displayed on the screen. The app will automatically configure the account.
</p>

<div class="bg-blue-50 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-800 rounded-lg p-4 my-4">
    <div class="flex">
        <svg class="w-5 h-5 text-blue-600 dark:text-blue-400 mr-3 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
        </svg>
        <div class="text-blue-800 dark:text-blue-200 text-sm">
            <p><strong>Can't scan the QR code?</strong></p>
            <p class="mt-1">Click "Enter code manually" to reveal a secret key you can type into your authenticator app instead.</p>
        </div>
    </div>
</div>

<h3>Step 4: Enter the Verification Code</h3>

<p>
    Your authenticator app will now show a 6-digit code that changes every 30 seconds. Enter the current code into Hay ACS to verify the setup.
</p>

<h3>Step 5: Complete Setup</h3>

<p>
    Click <strong>Enable 2FA</strong>. Your account is now protected with two-factor authentication.
</p>

<h2>Logging In with 2FA</h2>

<p>After 2FA is enabled, logging in works like this:</p>

<ol>
    <li>Enter your email and password as usual</li>
    <li>Click <strong>Log in</strong></li>
    <li>Open your authenticator app</li>
    <li>Enter the current 6-digit code</li>
    <li>Click <strong>Verify</strong></li>
</ol>

<div class="bg-green-50 dark:bg-green-900/30 border border-green-200 dark:border-green-800 rounded-lg p-4 my-4">
    <div class="flex">
        <svg class="w-5 h-5 text-green-600 dark:text-green-400 mr-3 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
        </svg>
        <p class="text-green-800 dark:text-green-200 text-sm">
            <strong>Tip:</strong> Enable "Trust this device for 90 days" on the 2FA verification page to skip this step on future logins from the same device.
        </p>
    </div>
</div>

<h2>Lost Access to Your Authenticator?</h2>

<p>
    If you lose your phone or can't access your authenticator app, contact your system administrator. An admin can reset your 2FA, which will give you a new 14-day grace period to set it up again.
</p>

<h2>Next Steps</h2>

<p>
    After setting up 2FA, consider enabling the <a href="{{ route('docs.show', ['section' => 'getting-started', 'page' => 'trusted-device']) }}">Trusted Device</a> feature to simplify future logins, especially if you work in the field.
</p>
@endsection
